name: OpenWrt-CI-x86_64 (TEST)

on:
  workflow_dispatch:

jobs:
  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-latest
    steps:
#   - name: Test
#     run : |
#       read -p "pause"

    - name: Initialization environment
      uses: ./.github/actions/Init.yml

    - name: Prepare Buildroot
      uses: ./.github/actions/Prepare.yml

    - name: Generate configuration file
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}
        rm -f ./.config*
        curl -Ls https://downloads.openwrt.org/releases/${{env.ver}}/targets/x86/64/config.buildinfo | grep -e CONFIG_TARGET_ -e CONFIG_KERNEL_ -e CONFIG_PACKAGE_ -e CONFIG_VERSION_ >> ./.config
        sed -i 's/CONFIG_TARGET_MULTI_PROFILE=y/CONFIG_TARGET_MULTI_PROFILE=n/' ./.config
        sed -i 's/CONFIG_TARGET_PER_DEVICE_ROOTFS=y/CONFIG_TARGET_PER_DEVICE_ROOTFS=n/' ./.config
        sed -i 's/CONFIG_TARGET_ALL_PROFILES=y/CONFIG_TARGET_ALL_PROFILES=n/' ./.config

        cat >> ./.config <<EOF
        # CONFIG_VHDX_IMAGES=y
        CONFIG_GRUB_EFI_IMAGES=y
        # CONFIG_TARGET_IMAGES_GZIP=n
        CONFIG_TARGET_ROOTFS_EXT4FS=y
        CONFIG_TARGET_ROOTFS_TARGZ=n
        CONFIG_TARGET_ROOTFS_SQUASHFS=n
        CONFIG_TARGET_ROOTFS_PARTSIZE=1024
        # CONFIG_TARGET_KERNEL_PARTSIZE=16
        # CONFIG_TARGET_EXT4_BLOCKSIZE_4K=y
        # CONFIG_TARGET_EXT4_BLOCKSIZE=4096
        EOF

        # cat >> ./.config <<EOF
        # CONFIG_PACKAGE_kmod-kvm-intel=y
        # CONFIG_PACKAGE_kmod-kvm-amd=y
        # CONFIG_PACKAGE_kmod-tun=y
        # CONFIG_PACKAGE_qemu-x86_64-softmmu=y
        # CONFIG_PACKAGE_qemu-bridge-helper=y
        # CONFIG_PACKAGE_qemu-img=y
        # EOF

        cat >> ./.config <<EOF
        CONFIG_PACKAGE_kmod-bnx2x=y
        CONFIG_PACKAGE_kmod-mt7921e=y
        CONFIG_PACKAGE_kmod-tcp-bbr=y
        CONFIG_PACKAGE_kmod-macvlan=y
        CONFIG_PACKAGE_kmod-fs-ext4=y
        CONFIG_PACKAGE_kmod-nft-tproxy=y
        CONFIG_PACKAGE_kmod-nft-netdev=y
        CONFIG_PACKAGE_bnx2x-firmware=y
        CONFIG_PACKAGE_libcap-bin=y
        CONFIG_PACKAGE_wpad-mbedtls=y
        CONFIG_PACKAGE_coreutils=y
        CONFIG_PACKAGE_coreutils-base64=y
        CONFIG_PACKAGE_coreutils-sha1sum=y
        CONFIG_PACKAGE_ca-certificates=y
        CONFIG_PACKAGE_dnsmasq=n
        CONFIG_PACKAGE_dnsmasq-full=y
        CONFIG_PACKAGE_ethtool-full=y
        CONFIG_PACKAGE_ip-full=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_irqbalance=y
        CONFIG_PACKAGE_tcpdump=y
        CONFIG_PACKAGE_iperf3=y
        CONFIG_PACKAGE_fdisk=y
        CONFIG_PACKAGE_parted=y
        CONFIG_PACKAGE_losetup=y
        CONFIG_PACKAGE_resize2fs=y
        CONFIG_PACKAGE_lsblk=y
        CONFIG_PACKAGE_blkid=y
        CONFIG_PACKAGE_block-mount=y
        CONFIG_PACKAGE_conntrack=y
        CONFIG_PACKAGE_bind-dig=y
        CONFIG_PACKAGE_drill=y
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_pciutils=y
        CONFIG_PACKAGE_proxychains-ng=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_hostapd-utils=y
        CONFIG_PACKAGE_uxc=y
        CONFIG_PACKAGE_sudo=y
        CONFIG_PACKAGE_python3-pip=y
        CONFIG_PACKAGE_xxd=y
        CONFIG_PACKAGE_cifsmount=y
        CONFIG_PACKAGE_screen=y
        CONFIG_PACKAGE_ncat-full=y
        CONFIG_PACKAGE_collectd-mod-thermal=y
        CONFIG_PACKAGE_collectd-mod-exec=y
        CONFIG_PACKAGE_collectd-mod-conntrack=y
        CONFIG_PACKAGE_collectd-mod-ipstatistics=y
        CONFIG_PACKAGE_collectd-mod-processes=y
        CONFIG_PACKAGE_collectd-mod-tcpconns=y
        CONFIG_PACKAGE_collectd-mod-uptime=y
        CONFIG_PACKAGE_collectd-mod-ping=y
        CONFIG_PACKAGE_collectd-mod-dns=y
        CONFIG_PACKAGE_xray-core=y
        # CONFIG_PACKAGE_podman=y
        # CONFIG_PACKAGE_v2raya=y
        # CONFIG_PACKAGE_sing-box=y
        # CONFIG_PACKAGE_logd=n
        # CONFIG_PACKAGE_syslog-ng=y
        # CONFIG_PACKAGE_rp-pppoe-relay=y
        # CONFIG_PACKAGE_3proxy=y
        CONFIG_PACKAGE_luci-proto-wireguard=y
        CONFIG_PACKAGE_luci-app-wol=y
        CONFIG_PACKAGE_luci-app-ddns=y
        CONFIG_PACKAGE_luci-app-mwan3=y
        CONFIG_PACKAGE_luci-app-samba4=y
        CONFIG_PACKAGE_luci-app-smartdns=y
        CONFIG_PACKAGE_luci-app-vnstat2=y
        CONFIG_PACKAGE_luci-app-statistics=y
        CONFIG_PACKAGE_luci-app-natmap=y
        CONFIG_PACKAGE_luci-app-upnp=y
        # CONFIG_PACKAGE_luci-app-dawn=y
        # CONFIG_PACKAGE_luci-app-nlbwmon=y
        # !! docker may use all space !!
        CONFIG_PACKAGE_luci-app-dockerman=y
        CONFIG_PACKAGE_luci-lib-docker=y
        EOF

        make defconfig

    - name: Build firmware
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}
        make -j$(nproc) || make -j1 V=s

    - name: Prepare artifact
      working-directory: ./openwrt
      run : |
        mkdir -p ./artifact/buildinfo
        mkdir -p ./artifact/firmware
        mkdir -p ./artifact/package
        cp ./.config ./artifact/buildinfo
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
        # rm -rf $(find ./artifact/firmware/ -type f -name "*.tar.gz")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.bin")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.img*" | grep -v "combined-efi")
        cp -rf $(find ./ -type f -regex '.*\.\(ipk\|apk\)$') ./artifact/package/

    - name: Deliver buildinfo
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_buildinfo_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/buildinfo/

    - name: Deliver firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/firmware/

    - name: Deliver package
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_package_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/package/
